### ISSUE TITLE
receiving output parse error in console

### ISSUE THREAD

**Issue by polygoncircus** [vimeo/vimeo-maxmsp#3]
Console Output, VimeoRequest.js: Javascript TypeError: body.files is undefined, line 19

from 19: outlet(0, body.files[1].link);

**Comment by reckoner165** [comment]
Hi @polygoncircus, was the video you were trying to access uploaded from your vimeo account?

**Comment by polygoncircus** [comment]
yes. key was generated, and video was mine.
console:
js: Sending GET request to api.vimeo.com  Received response. Parsing URL 
VimeoRequest.js: Javascript TypeError: body.files is undefined, line 19

**Comment by reckoner165** [comment]
@polygoncircus Your error is most likely a manifestation of bug #7 .
But if not, maybe the error logs in the latest release will help shed light on this.

**Comment by reckoner165** [comment]
This should be fixed with node4max integration in the latest version.
